### ISSUE TITLE
Run-time implementation

### ISSUE THREAD

**Issue by mike-caputo** [Unity-Technologies/AutoLOD#1]
Fantastic job, this is a welcome addition to the Unity eocsystem! In the Wiki I noticed:

* HLOD generation occurs at edit time (however, the framework doesn’t preclude having run-time generation)

I imagine this refers to a case where: the meshes & textures themselves are known at edit-time (already part of the Assets/ or Resources/ folder), and it is only their instances/transforms in the scene that are determined at run-time. Is it possible to take it a step further and say: the meshes & textures are living in an AssetBundle in StreamingAssets, so are not known at all until run-time?

**Comment by amirebrahimi** [comment]
The current implementation only runs in play mode in the editor, but with a little bit of work could be made to work in an actual build. It has a few dependencies on editor-only functionality, which is why that note exists. 

Separate from that there is also the possibility of having support for HLODs being generated at runtime, too, but that would require LOD solutions to support that, which currently Simplygon/InstaLOD do not to the best of my knowledge.
