### ISSUE TITLE
quadric mesh simplifier not working if simpygon.dll is in the project

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#10]
repro:
load the dll from this package https://forum.unity.com/threads/simplygon-login.498501/#post-3352846
import an object
= 
empty
but the lod0 mesh is there
https://i.imgur.com/LaLcDfE.png

**Comment by amirebrahimi** [comment]
I re-imported a model after importing the simplygon plugin into a project, but keeping Quadric Mesh Simplifier as the selected simplifier and it worked properly for me. Could you share more about the steps you took (perhaps even step-by-step from an entirely new project)? Could you make the model available, so that I could try and reproduce?

**Comment by laurentopia** [comment]
now it works :\
