### ISSUE TITLE
autoLOD create the wrong type of hiearchy

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#12]
https://i.imgur.com/FcBxTyB.png
why this is wrong:
doesn't drag and drop well, when you drag lod0 in the lodgroup bucket, it'll also drag lod1,2,3 all the children
instead the hierarchy needs to be like this:
house_small
   LOD0
       Layer_1_LOD0
       Layer_2_LOD0
   LOD1
      Layer_1_LOD1
      Layer_2_LOD1
...

**Comment by amirebrahimi** [comment]
Unfortunately, this is by design as it was necessary for HLOD processing to avoid having to use up layers or tags to differentiate LOD0s from other LODs. It also allows for getting to a parent LOD (i.e. LOD0 from LOD1) simply by walking the hierarchy even without a LODGroup being present or having to access a LODGroup, which is used in HLOD generation. We also didn't want to have to introduce yet another component to keep track of LODs on an object separate from the LODGroup. You're welcome to propose an alternative solution in a pull request if you think you can mitigate these issues and still maintain the current functionality. As of now, I won't have the bandwidth to make such a sweeping change to the system.

**Comment by laurentopia** [comment]
In the other thread you mentioned that lodgroup should be auto assigned after reimport, once I get it working that will take care of that.
