### ISSUE TITLE
autoLOD needs to auto set LODGroup

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#13]
since autoLOD is already creating the asset prefab for me, it should also auto set the LODGroup

**Comment by amirebrahimi** [comment]
It currently sets up the LODGroup in the asset prefab. Are you seeing otherwise? Can you post a screenshot?

**Comment by laurentopia** [comment]
Here you go https://i.imgur.com/hjyV7Sw.png
By the way it doesn't work with simplygon anymore, I revert back to the quadradic algo so no biggy but if you can take a look at the simplygon issue that's great.

**Comment by laurentopia** [comment]
ouch, quadratic really pokes hole everywhere in my mesh, so... simplygon working is kinda of a biggie
https://i.imgur.com/44Y4E52.png

**Comment by Camarent** [comment]
I think I know what is the problem because I had the same issue today. It happens when model has own lod group and the specified lod count in settings is different from lod count in model. So, SETLODs gives you this error: 
`SetLODs: Attempting to set LOD where the screen relative size is greater then or equal to a higher detail LOD level.
UnityEditor.AssetPostprocessingInternal:PostprocessMesh(GameObject)`

I created pull request with two changes. Maybe it will resolve your issue.

**Comment by amirebrahimi** [comment]
I think this is fixed now with #28

**Comment by chrono318** [comment]
LOD[] lods;
float a = 0.8f; float b = 0.5f;
lods[0] = new LOD( a, renderers1);
lods[1] = new LOD( b, renderers2);

a>b,so it's right;
**The error occurs when a<b.**  _SetLODs: Attempting to set LOD where the screen relative size is greater then or equal to a higher detail LOD level.
