### ISSUE TITLE
When deleting the AutoLOD folder, the folder comes back to life

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#22]
it's like a zombie, can't kill it

**Comment by amirebrahimi** [comment]
I tried this myself and couldn't reproduce. Are there any folders underneath it? Were you in a scene that had SceneLOD enabled?

**Comment by shazbit** [comment]
This happens with plugins that are still loaded. Remove it while the editor is closed.

**Comment by amirebrahimi** [comment]
Another person wrote a comment and then deleted it I believe, but I think it may be the answer to your problem -- it's likely you had a DLL in the folder or some other file that was locked that was keeping the directory from being deleted. 

I'm going to close this issue since it has lived for a while. If you encounter it again, then feel free to re-open or create a new issue.
