### ISSUE TITLE
What about ManualLod? 

### ISSUE THREAD

**Issue by friuns2** [Unity-Technologies/AutoLOD#27]
Can i generate lods manually? most of my models already have lods so i don't need lods been generated.

**Comment by amirebrahimi** [comment]
If your LODs are already in the model file using the naming convention detailed here:
https://docs.unity3d.com/Manual/LevelOfDetail.html
then AutoLOD won't try to generate LODs

Otherwise, if you are generating LODs manually, then you can turn off "generate on import" in the Preferences for AutoLOD.

**Comment by amirebrahimi** [comment]
You have to turn on the option once unfortunately in preferences, then generate the LODs, then turn it off and you can then override in the <model>_lods.asset file that sits next to the model. Perhaps I could have an easy way to create the LODs file, so this could be done without having to enable first in the preferences, but for now that is how you do it.

**Comment by amirebrahimi** [comment]
GameObject/AutoLOD/Generate LODs only works on a prefab though. It didn't work for you on an actual model (e.g. FBX) file, did it?

**Comment by amirebrahimi** [comment]
Added right-click to generate in 945423a
