### ISSUE TITLE
Compiler Error 2018.1.3f1

### ISSUE THREAD

**Issue by Theobarth** [Unity-Technologies/AutoLOD#35]
I have got this issue when importing in a 2018.1.3 project : 

Assets/AutoLOD/Scripts/Editor/MeshSimplifiers/QuadricMeshSimplifier.cs(2,7): error CS0246: The type or namespace name `UnityMeshSimplifier' could not be found. Are you missing an assembly reference?

The line are those
![devenv_2018-08-01_12-05-25](https://user-images.githubusercontent.com/40658548/43515621-3c8f7ea8-9583-11e8-9c5e-4c56b46051e4.png)

**Comment by duncanx** [comment]
I also have this issue in 2018.2

**Comment by Snow-Okami** [comment]
I had this same issue.

It is caused by downloading the AutoLOD package and not pulling it using git and the submodules the repo requires.

You can fix it by downloading and adding these 2 packages to your Unity Project (which are referenced [here](https://github.com/Unity-Technologies/AutoLOD/blob/master/.gitmodules) in the submodules):

[UnityMeshSimplifier](https://github.com/Unity-Technologies/UnityMeshSimplifier)
[ConditionalCompilationUtility](https://github.com/Unity-Technologies/ConditionalCompilationUtility)

After that, you MUST add a reference to UnityMeshSimplifier to your AutoLOD-Editor project. You can usually do this by right clicking the project in your IDE (I use Jetbrains)

![Add Reference](https://i.imgur.com/kc3EBKg.png)

**Comment by amirebrahimi** [comment]
The issue is that you cloned directly from the latest UnityMeshSimplifier instead of cloning recursively from master on this repository, which would get you the correct version of UnityMeshSimplifier. Either way, I've updated to the latest UnityMeshSimplifier in 84a096e.
