### ISSUE TITLE
Simulated Mesh Simplifier

### ISSUE THREAD

**Issue by chanfort** [Unity-Technologies/AutoLOD#4]
Firstly, nice work as for the first release.

While others are talking about Simplygon and InstaLOD, I noticed that there is also provided here the Simulated Mesh Simplifier. This one, different from other two, does not seem to require any external plugins and seems to be written from scratch.

I was trying to test a bit recently by importing high-polycount icosphere from Blender to Unity. The AutoLOD creates two additional LODs nicely. When I drag it into the scene, the main gameObject gets two child gameObject, where these two LODs are working. But when I zoom-in and out, the sphere disappears on LOD1, and appears back on the main LOD0. Is something not working here?

**Comment by amirebrahimi** [comment]
What you are seeing is by-design. The "Simulated" part of SimulatedMeshSimplifier is to simulate what a 50% reduction per LOD would bring. This simplifier essentially just punches polygons out at random until the target quality is met. This was created for testing purposes in order to iterate on AutoLOD and is still potentially useful for estimates. However, an actual LOD generator/simplifier needs to be used for production.

**Comment by chanfort** [comment]
Fair enough. Just a though that it might be still good if Unity would provide at least one its own simplifier. It should be quite easy to try some decimation algorithms, like average/median vertex clustering.

**Comment by amirebrahimi** [comment]
Yes, we had started work on a GPU-accelerated simplifier using QEM, but it was not robust enough to release.

**Comment by chanfort** [comment]
I guess these things takes time. I would imagine the first step could be non-optimised single threaded, second step multi-threaded CPU, and final step GPU-accelerated. Anyways, looking forward where this project will evolve.
