### ISSUE TITLE
SceneLOD and Multiple Scenes

### ISSUE THREAD

**Issue by Beowulfe222** [Unity-Technologies/AutoLOD#51]
Loving these plugins so far, but running into some issues with SceneLOD on one of my projects. It's a relatively large project, and is split into multiple scenes that are loaded additively on top of each other (using the plugin https://assetstore.unity.com/packages/tools/utilities/advanced-multi-scene-cross-scene-references-47200 - though I suspect the same issue would be present just using Unity's built-in additive scene system).

As far as I can tell, SceneLOD doesn't handle multiple scenes appropriately. I've tried to make some local changes to the code base to get it working properly, but haven't been able to get it fully functional yet. Is multiple scene support something that might be handled at some point, or should I start considering coding our own HLOD system?

**Comment by amirebrahimi** [comment]
You are correct. Multiple scene support is not supported. However, the details are important -- how would you want multiple scene support to work? Would you want each subscene to manage it's own HLOD levels independently? That'd be the easiest way to do it. Otherwise, if you want multiple subscenes to merge their HLODs, then you'd likely need a simplifier that'd work at runtime or at the very least you'd have to combine the meshes.

If you're planning to code your own HLOD system, then perhaps we can collaborate on adding this feature. I don't have a lot of cycles for this project currently, but if we get clear on what is needed, then the work you'd do anyway could benefit the project. So, I'd be willing to see what would be needed on my end to support.
