### ISSUE TITLE
not usable: it creates holes alongside UV boundaries

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#6]
https://i.imgur.com/rm35rUm.png

**Comment by amirebrahimi** [comment]
What simplifier are you using?

**Comment by laurentopia** [comment]
Quadric

**Comment by laurentopia** [comment]
and simulated destroys every 2 triangles resulting in this
https://i.imgur.com/nLdo1VW.png

**Comment by amirebrahimi** [comment]
Yes, simulated is just that - a simulation of what gains you could expect, but essentially much quicker at generating. It might need a rename to FakeSimplifier perhaps to be more clear.

Re: the Quadric, that is from this GitHub project: https://github.com/Whinarn/UnityMeshSimplifier. You could post an issue there, but that simplifier is based on https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification, which might be where the actual problem lies.

If you have Simplygon or InstaLOD you may see better results.

The AutoLOD framework is built in such a way that any mesh simplifier could easily plug into the system.

**Comment by laurentopia** [comment]
the model
https://drive.google.com/a/elefantopia.com/uc?id=1qy57PboJs1AF5siCPEeHQGf4jwJxH4Yv

**Comment by laurentopia** [comment]
which version of simpligon needs to be installed?

**Comment by amirebrahimi** [comment]
8.2.X, but unfortunately they pulled their existing Unity plugin and still have not published a new one. I pointed this out on their forum and have not heard a response back. The old plugin worked fine in my tests.

If you're registered on their forums, this is the post: https://simplygon.freshdesk.com/support/discussions/topics/5000086159

**Comment by laurentopia** [comment]
I saw that only ue has an installer, is the old plugin available somewhere?

**Comment by amirebrahimi** [comment]
Not that I can see. If you happen to find another good simplifier that works well for your model, I'd be willing to write implement an ISimplifier wrapper for it, similar to the other simplifiers.

**Comment by laurentopia** [comment]
This one is ok https://github.com/wjakob/instant-meshes

**Comment by amirebrahimi** [comment]
This was suggested in #2, but it looks like there are some concerns about how well it would work for simplification. I haven't looked into it further.

**Comment by laurentopia** [comment]
Yes I have used it, it's quite good at simplification as it keeps the flow of the mesh but it doesn't transfer UVs...

**Comment by laurentopia** [comment]
oh, did you see that? you need to set a flag to keep the borders https://github.com/Whinarn/UnityMeshSimplifier/issues/2

**Comment by amirebrahimi** [comment]
Yes, I was aware of this. When I talked with @Whinarn it seemed like better results were reached with the preserve borders flag turned off, but I'll look into defaulting this to true perhaps and/or providing a way for custom options to be set on a selected simplifier.

Re: instant-meshes, it's great to hear that it does a good job for simplification for you, but without transferring UVs I see that as a big miss for attempting to integrate into AutoLOD. Don't you agree?

**Comment by Whinarn** [comment]
The reason preserving borders was turned off by default was that it restricted the simplification, and mostly only worked on high poly meshes. But only to a certain polygon count since the border edges are never removed. So while it makes sure that holes doesn't get created, it ends up being bad at the actual mesh simplification in many cases. So I would personally think that providing options would be a better idea instead of defaulting it.

**Comment by laurentopia** [comment]
@Whinarn improved the quadratic decimation algorithm. See if the WIP branch works for you, I think it's ready to be used in autolod as is.
https://github.com/Whinarn/UnityMeshSimplifier/issues/2#issuecomment-365803966

**Comment by Whinarn** [comment]
Oh I don't recommend that they use it just yet, since it's a work in progress. I only meant to show my current progress if you were interested in trying it out yourself. Sorry if I didn't make that clear.

I'm trying to finish it up when I have some time over, but I want to make sure that it works a lot better before I suggest that people start using it.

**Comment by laurentopia** [comment]
Oh ok.

**Comment by laurentopia** [comment]
Thank you Whinarn, I will try it as soon as it's in AutoLOD.

**Comment by amirebrahimi** [comment]
Updated to latest with ed3c61f
