### ISSUE TITLE
When creating LODs for prefab, create LODs asset next to mesh

### ISSUE THREAD

**Issue by redwyre** [Unity-Technologies/AutoLOD#73]
When I use "Generate LOD" on a prefab, it creates a `<prefabname>_lods.asset` file (no settings).
When I use "Generate LOD" on a model (fbx file), it creates a `<modelname>_logs.asset` file with settings.

Is there a way to make updating a prefab create the asset file with the model, or use it if it exists already? I have a number of prefabs with shared models and it's generating new meshes for each one.

A workaround seems to be individually selecting meshes (it doesn't work with multiselect) and "Generate LOD" there, then "Generate LOD" on the prefab seems to re-use the existing lods asset.

**Comment by amirebrahimi** [comment]
Hmm...I'm not sure I completely follow. I'll clarify a few things though. Even though both files have the `.asset` extension creating LODs from a prefab is different than the model version because the model version goes through the importer process. As such, this is why you only see the settings on the model file.

The idea here is that if you can tweak your model import to generate LODs the way you want them with settings, then you should be able to use the model "prefab" directly without having to create a separate prefab.

If what you are asking is whether you could update your custom prefab, which is based on the imported model automagically I think there would be more work than I can currently commit to for that.

I've answered your other question #72 and perhaps that will help you with this question if it is related.
