### ISSUE TITLE
Is AutoLOD still a thing? Is there a Unity registry to use in the Package Manager?

### ISSUE THREAD

**Issue by crdmrn** [Unity-Technologies/AutoLOD#79]
This is an extremely needed feature and would be nice if it wasn't dropped.
Also, I really don't understand why from one side Unity is trying to move all the plugins management to the Package system, and on the other side GitHub is still full of these half-hidden repositories.
Would it be possible to compile a preview or experimental package for AutoLOD?

**Comment by amirebrahimi** [comment]
Hi @crdmrn,

Thank you for your message. There is no longer active development on AutoLOD, but I do try and fix any pressing issues that arise. The last update was to allow [installation via the package manager by using a git url](https://github.com/Unity-Technologies/AutoLOD#install-via-package-manager). There are new requirements internally for packages following in the footsteps of this [blogpost](https://blogs.unity3d.com/2020/06/24/package-manager-updates-in-unity-2020-1/) from last year that prevents this from becoming preview since there is no plan for an official release. What also changed was how we treat experimental packages. Essentially, you are looking at one. They are not discoverable in the package manager and require you to install via URL. My understanding is that this all came about because of developers disliking having unfinished packages in the form of preview showing up in Unity, which implied that they were close to production quality. I think what was being communicated from customers was "do less, do it well".

I hear your frustrations and while I know there have been a few projects internally there is no official answer that I am aware of for a full solution. AutoLOD was a project that started here in Labs to perform research and although we tried our best to communicate that it was not a part of the official product -- I get that this is not something creators who use Unity really care about.

**Comment by crdmrn** [comment]
Honestly, how is it even possible that creators don't want a built-in LOD solution? Where did you get this idea?
LODs are one of the very basics of games optimization, and there's nothing more tedious than making them by hand.
For anyone working on a mobile/switch project or a high-quality console or pc game for commercial release (and not just a game jam or amateur project) LODs are a life saver, and a good, built-in implementation would save tons of work hours.
Tbh, as a customer, I would like a game engine that strives towards implementing technologies aimed at making professional game development better and to have better final results; what I see is a lot of insecurity towards who do you want your customers/users to be, paired with questionable advertisement on how cool is to use Unity to build slot machines.
I've been a Unity user for ages, and never lost a chance to praise it, but it's really becoming hard lately :/

**Comment by amirebrahimi** [comment]
To clarify - what I meant by "I get that this is not something creators who use Unity really care about" is that I think people who use Unity don't care about whether a project came about as a part of a research project from Labs or by official means from our R&D team. In the end Unity users just see a single company.

I think a built-in LOD solution with _sensible defaults_ is incredibly important. That is why I created AutoLOD in the first place.
