### ISSUE TITLE
autoLOD is aids

### ISSUE THREAD

**Issue by enaisnotanumber** [Unity-Technologies/AutoLOD#97]
that is all, i refuse to elaborate. thanks guys

**Comment by enaisnotanumber** [comment]
my gun is literally just a figment of my imagination now
![image](https://github.com/Unity-Technologies/AutoLOD/assets/131741963/934cb7bd-595c-4f42-aba4-537a45c8675f)

**Comment by StCost** [comment]
I hope you had a backup of your game. 
Did corruption happened right when you installed the package?
I guess it could happen because of auto-generating on import, which was left "true" by default in source code. Maybe my [fork ](https://github.com/StCost/AutoLOD) won't do that (can't garantee), when you'll give AutoLOD another try

**Comment by enaisnotanumber** [comment]
i was able to fix the issues by just going back through my project & reenabling a ton of mesh renderers, so it's good now
